name: CI-Workflow
 
on:
  push:
    branches:
      - main
    paths:
      - '/workspaces/github-actions/src/main/java/com/mycompany/app/app.java'
      - '**/**/*.yaml'

jobs:
  build-linux:
    name: Build on Ubuntu with Java 21
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

  build-windows:
    name: Build on Windows with Java 21
    runs-on: windows-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '11
 
      - name: Build with Maven
        run: mvn clean install