name: CI-Workflow
 
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**'
  #     - '**/**/*.yaml'

jobs:
  build-linux:
    name: Build on Ubuntu with Java 17
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  build-windows:
    name: Build on Windows with Java 21
    runs-on: windows-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Build with Maven
        run: mvn clean install

  wild-notifications:
    name: Report Build Status
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    if: always()  # Ensures this job runs even if others fail
    steps:
      - name: Print status of all jobs
        run: |
          echo "Build Results:"
          echo "Linux: ${{ needs.build-linux.result }}"
          echo "Windows: ${{ needs.build-windows.result }}"

      - name: Fail if any build failed
        if: ${{ needs.build-linux.result == 'failure' || needs.build-windows.result == 'failure' }}
        run: |
          echo "One or more builds failed"
          exit 1
