name: CI-Workflow
 
on:
  push:
    branches:
      - main
    paths:
      - '/workspaces/github-actions/src/**'
      - '**/**/*.yaml'

jobs:
  build-linux:
    name: Build on Ubuntu with Java 17
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  build-windows:
    name: Build on Windows with Java 21
    runs-on: windows-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Build with Maven
        run: mvn clean install

  build-notifications:
    name:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    
    steps:
      - name: Check job status
        if: ${{ needs.build-windows.result == 'failure' || needs.build-linux.result == 'failure' }}
        run: echo "One of the builds failed."