name: Java Build and Deploy
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, production)'
        required: true
        default: 'main'
 
env:
  GLOBAL_ENV_VAR: 'enabled'
 
jobs:
  build:
    name: Build Java App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: [11, 17]
        os: [ubuntu-latest, windows-latest]
    outputs:
      build-dir: ${{ steps.set-output.outputs.build-dir }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
 
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
 
      - name: Build with Gradle
        run: ./gradlew build
 
      - name: Publish artifacts
        id: set-output
        run: |
          mkdir -p artifacts
          cp build/libs/*.jar artifacts/
          echo "build-dir=artifacts" >> $GITHUB_OUTPUT
 
  deploy:
    name: Deploy Java App
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment }}
 
    steps:
      - name: Use build output
        run: echo "Deploying from ${{ needs.build.outputs.build-dir }}"
 
      - name: Deploy app
        run: |
          echo "Deploying JAR to ${{ github.event.inputs.environment }} environment"
          ls ${{ needs.build.outputs.build-dir }}
 
      - name: Use secret
        run: echo "Secret token ${{ secrets.DEPLOY_TOKEN }}"
 
      - name: Use global variable
        run: echo "Global variable $GLOBAL_ENV_VAR" 