name: Java Build and Deploy
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, production)'
        required: true
        default: 'dev'
 
env:
  GLOBAL_ENV_VAR: 'enabled'
 
jobs:
  build:
    name: Build Java App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: [ 17 ]
        os: [ubuntu-latest, windows-latest]
    outputs:
      build-dir: ${{ steps.set-output.outputs.build-dir }}
    environment: ${{ github.event.inputs.environment }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show PASSWORD & user name
        run: |
          echo "PASSWORD is set but hidden MY_SECRET ${{ secrets.PASSWORD }} "
          echo "User_name is set but hidden MY_SECRET ${{ vars.USER_NAME }} "
          
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn clean install
 
      - name: Publish artifacts
        id: set-output
        run: |
          mkdir -p artifacts
          cp /home/runner/work/github-actions/github-actions/target/*.jar artifacts/
          echo "build-dir=artifacts" >> $GITHUB_OUTPUT
 
  deploy:
    name: Deploy Java App
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment }}
 
    steps:
      - name: Use build output
        run: echo "Deploying from ${{ needs.build.outputs.build-dir }}"
 
      - name: Deploy app
        run: |
          echo "Deploying JAR to ${{ github.event.inputs.environment }} environment"
          ls ${{ needs.build.outputs.build-dir }}
 
      - name: Use secret
        run: echo "Secret token ${{ secrets.DEPLOY_TOKEN }}"
 
      - name: Use global variable
        run: echo "Global variable $GLOBAL_ENV_VAR" 
