name: Context Demo
 
on:
  workflow_dispatch:
 
env:
  GLOBAL_ENV_VAR: "I am a global env variable"
 
jobs:
  show-contexts:
    name: Show Contexts
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Show GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
 
      - name: Show Environment Variable
        run: |
          echo "Global ENV VAR: $GLOBAL_ENV_VAR"
        env:
          LOCAL_ENV_VAR: "I am local"
      
      - name: Show Custom Repository Variable
        run: |
          echo "Repo Variable: ${{ vars.MY_REPO_VAR }}"
        # Set MY_REPO_VAR in GitHub > Settings > Repository > Variables
 
      - name: Show Secret
        run: |
          echo "Secret is set but hidden."
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        # Set MY_SECRET in GitHub > Settings > Secrets
