name: Filter Workflow
 
on:
  push:
    branches:
      - main
      - 'release/*'        # Wildcard branch filter
    tags:
      - 'v*'               # Tag filter for releases like v1.0, v2.1.3
    paths:
      - 'src/**'           # Only run when files in src/ are changed
      - '!docs/**'         # Ignore changes in docs/
 
  pull_request:
    branches:
      - develop
    paths:
      - '**.js'
      - '!test/**'
 
jobs:
  filtered-job:
    name: Run if filters match
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Show info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Triggered by: ${{ github.event_name }}"
