name: Lint Code

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run custom ESLint Action
        uses: ./github/actions/eslint
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
