name: CI-Workflow
 
on:
  fork: 
  pull_request_review:
    types: [ submitted, edited ]

jobs:
  build-linux:
    name: Build on Ubuntu with Java 17
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
