name: Environment Test
 
on:
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        description: 'Target Environment'
        required: true
        default: stg
        type: environment
 
jobs:
  environment-echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET_ENV }}
 
    steps:
      - name: Echo Environment Variables
        run: |
          echo "Env var USERNAME: ${{ vars.USER_NAME }}"
          echo "Env secret API_KEY: ${{ secrets.PASSWORD }}"